<?php

/**
 * @file
 * Contains fitpreg.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fitpreg_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitpreg module.
    case 'help.page.fitpreg':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for making general tasks and alterations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fitpreg_theme() {
  return [
    'fitpreg' => [
      'render element' => 'children',
    ],
  ];
}
