<?php

/**
 * @file
 * Contains fitpregnancy.module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fitpregnancy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitpregnancy module.
    case 'help.page.fitpregnancy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for making general tasks and alterations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fitpregnancy_theme() {
  return [
    'fitpregnancy' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function fitpregnancy_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  $excess_links = array('Pregnancy', 'Baby names', 'Nutrition', 'Baby', 'More', 'Exercise', 'Parenting');
  $links = $breadcrumb->getLinks();
//  kint($breadcrumb);
  foreach ($links as $index=>$link) {
    $target = $link->getText();
    if (in_array($target, $excess_links)) {
      unset($links[$index]);
    }
  }
  $breadcrumb = new Breadcrumb();
  $breadcrumb->setLinks($links);
}