<?php

/**
 * @file
 * Contains fitpregnancy.module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function fitpregnancy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitpregnancy module.
    case 'help.page.fitpregnancy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for making general tasks and alterations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fitpregnancy_theme() {
  return [
    'fitpregnancy' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function fitpregnancy_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  $excess_links = array('Pregnancy', 'Baby names', 'Nutrition', 'Baby', 'More', 'Exercise', 'Parenting');
  $links = $breadcrumb->getLinks();
//  kint($breadcrumb);
  foreach ($links as $index=>$link) {
    $target = $link->getText();
    if (in_array($target, $excess_links)) {
      unset($links[$index]);
    }
  }
  $breadcrumb = new Breadcrumb();
  $breadcrumb->setLinks($links);
}

/**
 * Implements hook_views_query_alter().
 * @param ViewExecutable $view
 * @param QueryPluginBase $query
 */
function fitpregnancy_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  /*
   * Change sort criteria: set sort by integer (default DB field type is char)
   */
  if ($view->id() == 'weeks' && $view->current_display === 'page_1') {
    if ($query->orderby[0]['field'] == 'node__field_week_field_week_value') {
      $query->addOrderBy(NULL, "CONVERT(node__field_week.field_week_value, SIGNED)", 'ASC', 'order_field');
      $sorting = $query->orderby[1]['field'];
      $query->orderby[0]['field'] = $sorting;
      unset($query->orderby[1]);
    }
  }
}